FROM node:24-alpine

WORKDIR /app

# Install dependencies first to leverage Docker cache
COPY package.json package-lock.json* ./
# RUN npm ci --only=production
RUN npm install

# Copy source code
COPY . .

# Set environment variables
ENV PORT=3001
ENV NODE_ENV=production

EXPOSE 3001

# Start the application
CMD ["node", "src/index.js"]